version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    resource_class: 2xlarge
    steps:
      - checkout
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: sleep 9h
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output